import type { StarlightUserConfig } from '@astrojs/starlight/types';

// The two browser tools are plain Astro pages, not content-collection entries,
// so they exist at one URL each and have no per-locale build. Starlight
// localizes every sidebar `link:` it does not recognise as external, which would
// point the Korean sidebar at `/ko/config-editor/` — a page that is never built.
// `src/routeData.ts` un-localizes exactly these hrefs again.
export const UNLOCALIZED_LINKS = ['/config-editor/', '/phonebook-converter/'];

// Explicit rather than autogenerated: the order is a reading order, not an
// alphabetical one, and it is the main thing that tells a first-time operator
// what to do next.
export const sidebar: StarlightUserConfig['sidebar'] = [
	{ slug: 'index' },
	{
		label: 'Setting up',
		translations: { ko: '설치하기' },
		items: [
			{ slug: 'setup/quick-start' },
			{ slug: 'setup/your-sheet' },
			{
				label: 'Phone book converter',
				translations: { ko: 'phone_book.json 변환기' },
				link: '/phonebook-converter/',
			},
			{ slug: 'setup/deploying' },
		],
	},
	{
		label: 'Rank styles',
		translations: { ko: '등급 스타일' },
		items: [{ slug: 'ranks/choosing' }, { slug: 'ranks/scale' }],
	},
	{
		label: 'Configuration',
		translations: { ko: '설정' },
		items: [
			{ slug: 'config/reference' },
			{ label: 'Config editor', link: '/config-editor/' },
		],
	},
	{
		label: 'Graph tool integration',
		translations: { ko: '그래프 툴 연동' },
		items: [{ slug: 'integration/cringraph' }, { slug: 'integration/moderngraphtool' }],
	},
];
